//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class test_user
{
    public long ID { get; set; }
    public string ID_String { get; set; }
    public string Android_Version { get; set; }
    public string PaymentType { get; set; }
    public string Remark { get; set; }
    public Nullable<System.DateTime> CreatedOn { get; set; }
}
